### ISSUE TITLE
Misc amends - changes to copy of help section

### ISSUE THREAD

**Issue by clairevgarnett** [UCL-Centre-for-Behaviour-Change/DrinkLess#2]
Update the copy for the Help -> The team section with the below.

> _If you use this app to help you drink less alcohol you're in good hands. The app has been developed by a highly qualified team of experts based at University College London, with support from leading researchers from other universities. Professor Susan Michie and Professor Robert West both have extensive experience in helping people achieve behaviour change goals. Dr Jamie Brown led a successful project called StopAdvisor to help smokers quit and runs ongoing studies about alcohol use. Dr David Crane has developed a very popular app called [Smoke Free] and Dr Claire Garnett is a researcher specialising in behaviour change apps. We've developed this app to study whether it helps people drink less alcohol so we can learn how to do this better. We will publish our findings so that others can benefit. So by using the app you're not only helping yourself but are helping science too. Thank you. This research was funded by the UK Centre for Tobacco and Alcohol Studies (UKCTAS), the NIHR School for Public Health Research (NIHR SPHR), the Society for the Study of Addiction (SSA) and Cancer Research UK (CRUK). The views expressed are those of the author(s) and not necessarily those of the NHS, the NIHR or the Department of Health. UKCTAS is a UKCRC Public Health Research Centre of Excellence. Funding from the Medical Research Council, British Heart Foundation, Cancer Research UK, Economic and Social Research Council and the National Institute for Health Research under the auspices of the UK Clinical Research Collaboration, is gratefully acknowledged._

**Comment by Air-Craft** [comment]
done
